version: '3'

services:

  mealy-database:
    image: 'mysql:8.0.25'
    container_name: mealy-database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mealyuser
      - MYSQL_PASSWORD=mealypass
      - MYSQL_DATABASE=mealy
      - MYSQL_TCP_PORT=3307
    ports:
      - '3307:3307'
    volumes:
      - ~/devel/private/dockers/mysql/data:/var/lib/mysql
